namespace Matrix
{
    partial class MainForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MainForm));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.bunifuElipse1 = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.bunifuShadowPanel1 = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.PaymentButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.MembersButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.ExpenseButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.UsersButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.IncomeButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.RenewButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.DashboardButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.MainPanel = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.MinimizeAppButton = new Bunifu.UI.WinForms.BunifuImageButton();
            this.CloseButton = new Bunifu.UI.WinForms.BunifuImageButton();
            this.Update = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuShadowPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuElipse1
            // 
            this.bunifuElipse1.ElipseRadius = 25;
            this.bunifuElipse1.TargetControl = this;
            // 
            // bunifuShadowPanel1
            // 
            this.bunifuShadowPanel1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel1.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel1.BorderRadius = 15;
            this.bunifuShadowPanel1.BorderThickness = 1;
            this.bunifuShadowPanel1.Controls.Add(this.Update);
            this.bunifuShadowPanel1.Controls.Add(this.PaymentButton);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuLabel1);
            this.bunifuShadowPanel1.Controls.Add(this.pictureBox1);
            this.bunifuShadowPanel1.Controls.Add(this.MembersButton);
            this.bunifuShadowPanel1.Controls.Add(this.ExpenseButton);
            this.bunifuShadowPanel1.Controls.Add(this.UsersButton);
            this.bunifuShadowPanel1.Controls.Add(this.IncomeButton);
            this.bunifuShadowPanel1.Controls.Add(this.RenewButton);
            this.bunifuShadowPanel1.Controls.Add(this.DashboardButton);
            this.bunifuShadowPanel1.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Solid;
            this.bunifuShadowPanel1.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.bunifuShadowPanel1.Location = new System.Drawing.Point(2, 29);
            this.bunifuShadowPanel1.Name = "bunifuShadowPanel1";
            this.bunifuShadowPanel1.PanelColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(105)))), ((int)(((byte)(105)))));
            this.bunifuShadowPanel1.PanelColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(105)))), ((int)(((byte)(105)))));
            this.bunifuShadowPanel1.ShadowColor = System.Drawing.Color.DarkGray;
            this.bunifuShadowPanel1.ShadowDept = 2;
            this.bunifuShadowPanel1.ShadowDepth = 2;
            this.bunifuShadowPanel1.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Surrounded;
            this.bunifuShadowPanel1.ShadowTopLeftVisible = false;
            this.bunifuShadowPanel1.Size = new System.Drawing.Size(231, 702);
            this.bunifuShadowPanel1.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.bunifuShadowPanel1.TabIndex = 0;
            // 
            // PaymentButton
            // 
            this.PaymentButton.AllowAnimations = true;
            this.PaymentButton.AllowMouseEffects = true;
            this.PaymentButton.AllowToggling = false;
            this.PaymentButton.AnimationSpeed = 200;
            this.PaymentButton.AutoGenerateColors = false;
            this.PaymentButton.AutoRoundBorders = false;
            this.PaymentButton.AutoSizeLeftIcon = true;
            this.PaymentButton.AutoSizeRightIcon = true;
            this.PaymentButton.BackColor = System.Drawing.Color.Transparent;
            this.PaymentButton.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(105)))), ((int)(((byte)(105)))));
            this.PaymentButton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("PaymentButton.BackgroundImage")));
            this.PaymentButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.PaymentButton.ButtonText = "Payment";
            this.PaymentButton.ButtonTextMarginLeft = 0;
            this.PaymentButton.ColorContrastOnClick = 45;
            this.PaymentButton.ColorContrastOnHover = 45;
            this.PaymentButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.PaymentButton.CustomizableEdges = borderEdges2;
            this.PaymentButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.PaymentButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.PaymentButton.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.PaymentButton.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.PaymentButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.PaymentButton.Font = new System.Drawing.Font("Bebas", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.PaymentButton.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(30)))), ((int)(((byte)(70)))));
            this.PaymentButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.PaymentButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.PaymentButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.PaymentButton.IconMarginLeft = 11;
            this.PaymentButton.IconPadding = 10;
            this.PaymentButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.PaymentButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.PaymentButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.PaymentButton.IconSize = 25;
            this.PaymentButton.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(248)))), ((int)(((byte)(232)))));
            this.PaymentButton.IdleBorderRadius = 15;
            this.PaymentButton.IdleBorderThickness = 1;
            this.PaymentButton.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(105)))), ((int)(((byte)(105)))));
            this.PaymentButton.IdleIconLeftImage = null;
            this.PaymentButton.IdleIconRightImage = null;
            this.PaymentButton.IndicateFocus = true;
            this.PaymentButton.Location = new System.Drawing.Point(23, 450);
            this.PaymentButton.Name = "PaymentButton";
            this.PaymentButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.PaymentButton.OnDisabledState.BorderRadius = 15;
            this.PaymentButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.PaymentButton.OnDisabledState.BorderThickness = 1;
            this.PaymentButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.PaymentButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.PaymentButton.OnDisabledState.IconLeftImage = null;
            this.PaymentButton.OnDisabledState.IconRightImage = null;
            this.PaymentButton.onHoverState.BorderColor = System.Drawing.Color.White;
            this.PaymentButton.onHoverState.BorderRadius = 15;
            this.PaymentButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.PaymentButton.onHoverState.BorderThickness = 1;
            this.PaymentButton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(199)))), ((int)(((byte)(0)))), ((int)(((byte)(57)))));
            this.PaymentButton.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(30)))), ((int)(((byte)(70)))));
            this.PaymentButton.onHoverState.IconLeftImage = null;
            this.PaymentButton.onHoverState.IconRightImage = null;
            this.PaymentButton.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(248)))), ((int)(((byte)(232)))));
            this.PaymentButton.OnIdleState.BorderRadius = 15;
            this.PaymentButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.PaymentButton.OnIdleState.BorderThickness = 1;
            this.PaymentButton.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(105)))), ((int)(((byte)(105)))));
            this.PaymentButton.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(30)))), ((int)(((byte)(70)))));
            this.PaymentButton.OnIdleState.IconLeftImage = null;
            this.PaymentButton.OnIdleState.IconRightImage = null;
            this.PaymentButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.PaymentButton.OnPressedState.BorderRadius = 15;
            this.PaymentButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.PaymentButton.OnPressedState.BorderThickness = 1;
            this.PaymentButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.PaymentButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.PaymentButton.OnPressedState.IconLeftImage = null;
            this.PaymentButton.OnPressedState.IconRightImage = null;
            this.PaymentButton.Size = new System.Drawing.Size(182, 39);
            this.PaymentButton.TabIndex = 20;
            this.PaymentButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.PaymentButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.PaymentButton.TextMarginLeft = 0;
            this.PaymentButton.TextPadding = new System.Windows.Forms.Padding(0);
            this.PaymentButton.UseDefaultRadiusAndThickness = true;
            this.PaymentButton.Click += new System.EventHandler(this.PaymentButton_Click);
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Bebas", 15.75F);
            this.bunifuLabel1.Location = new System.Drawing.Point(19, 163);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(192, 25);
            this.bunifuLabel1.TabIndex = 19;
            this.bunifuLabel1.Text = "Gym Management System";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // pictureBox1
            // 
            this.pictureBox1.BackColor = System.Drawing.Color.Transparent;
            this.pictureBox1.Image = global::Matrix.Properties.Resources.Asad_LOGO_transparent;
            this.pictureBox1.Location = new System.Drawing.Point(19, 17);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(190, 138);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox1.TabIndex = 8;
            this.pictureBox1.TabStop = false;
            // 
            // MembersButton
            // 
            this.MembersButton.AllowAnimations = true;
            this.MembersButton.AllowMouseEffects = true;
            this.MembersButton.AllowToggling = false;
            this.MembersButton.AnimationSpeed = 200;
            this.MembersButton.AutoGenerateColors = false;
            this.MembersButton.AutoRoundBorders = false;
            this.MembersButton.AutoSizeLeftIcon = true;
            this.MembersButton.AutoSizeRightIcon = true;
            this.MembersButton.BackColor = System.Drawing.Color.Transparent;
            this.MembersButton.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(105)))), ((int)(((byte)(105)))));
            this.MembersButton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("MembersButton.BackgroundImage")));
            this.MembersButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.MembersButton.ButtonText = "Add Members";
            this.MembersButton.ButtonTextMarginLeft = 0;
            this.MembersButton.ColorContrastOnClick = 45;
            this.MembersButton.ColorContrastOnHover = 45;
            this.MembersButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.MembersButton.CustomizableEdges = borderEdges3;
            this.MembersButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.MembersButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.MembersButton.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.MembersButton.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.MembersButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.MembersButton.Font = new System.Drawing.Font("Bebas", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.MembersButton.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(30)))), ((int)(((byte)(70)))));
            this.MembersButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.MembersButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.MembersButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.MembersButton.IconMarginLeft = 11;
            this.MembersButton.IconPadding = 10;
            this.MembersButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.MembersButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.MembersButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.MembersButton.IconSize = 25;
            this.MembersButton.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(248)))), ((int)(((byte)(232)))));
            this.MembersButton.IdleBorderRadius = 15;
            this.MembersButton.IdleBorderThickness = 1;
            this.MembersButton.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(105)))), ((int)(((byte)(105)))));
            this.MembersButton.IdleIconLeftImage = null;
            this.MembersButton.IdleIconRightImage = null;
            this.MembersButton.IndicateFocus = true;
            this.MembersButton.Location = new System.Drawing.Point(23, 284);
            this.MembersButton.Name = "MembersButton";
            this.MembersButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.MembersButton.OnDisabledState.BorderRadius = 15;
            this.MembersButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.MembersButton.OnDisabledState.BorderThickness = 1;
            this.MembersButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.MembersButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.MembersButton.OnDisabledState.IconLeftImage = null;
            this.MembersButton.OnDisabledState.IconRightImage = null;
            this.MembersButton.onHoverState.BorderColor = System.Drawing.Color.White;
            this.MembersButton.onHoverState.BorderRadius = 15;
            this.MembersButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.MembersButton.onHoverState.BorderThickness = 1;
            this.MembersButton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(199)))), ((int)(((byte)(0)))), ((int)(((byte)(57)))));
            this.MembersButton.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(30)))), ((int)(((byte)(70)))));
            this.MembersButton.onHoverState.IconLeftImage = null;
            this.MembersButton.onHoverState.IconRightImage = null;
            this.MembersButton.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(248)))), ((int)(((byte)(232)))));
            this.MembersButton.OnIdleState.BorderRadius = 15;
            this.MembersButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.MembersButton.OnIdleState.BorderThickness = 1;
            this.MembersButton.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(105)))), ((int)(((byte)(105)))));
            this.MembersButton.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(30)))), ((int)(((byte)(70)))));
            this.MembersButton.OnIdleState.IconLeftImage = null;
            this.MembersButton.OnIdleState.IconRightImage = null;
            this.MembersButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.MembersButton.OnPressedState.BorderRadius = 15;
            this.MembersButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.MembersButton.OnPressedState.BorderThickness = 1;
            this.MembersButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.MembersButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.MembersButton.OnPressedState.IconLeftImage = null;
            this.MembersButton.OnPressedState.IconRightImage = null;
            this.MembersButton.Size = new System.Drawing.Size(182, 39);
            this.MembersButton.TabIndex = 2;
            this.MembersButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.MembersButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.MembersButton.TextMarginLeft = 0;
            this.MembersButton.TextPadding = new System.Windows.Forms.Padding(0);
            this.MembersButton.UseDefaultRadiusAndThickness = true;
            this.MembersButton.Click += new System.EventHandler(this.MembersButton_Click);
            // 
            // ExpenseButton
            // 
            this.ExpenseButton.AllowAnimations = true;
            this.ExpenseButton.AllowMouseEffects = true;
            this.ExpenseButton.AllowToggling = false;
            this.ExpenseButton.AnimationSpeed = 200;
            this.ExpenseButton.AutoGenerateColors = false;
            this.ExpenseButton.AutoRoundBorders = false;
            this.ExpenseButton.AutoSizeLeftIcon = true;
            this.ExpenseButton.AutoSizeRightIcon = true;
            this.ExpenseButton.BackColor = System.Drawing.Color.Transparent;
            this.ExpenseButton.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(105)))), ((int)(((byte)(105)))));
            this.ExpenseButton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ExpenseButton.BackgroundImage")));
            this.ExpenseButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.ExpenseButton.ButtonText = "Manage Expenses";
            this.ExpenseButton.ButtonTextMarginLeft = 0;
            this.ExpenseButton.ColorContrastOnClick = 45;
            this.ExpenseButton.ColorContrastOnHover = 45;
            this.ExpenseButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.ExpenseButton.CustomizableEdges = borderEdges4;
            this.ExpenseButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.ExpenseButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.ExpenseButton.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ExpenseButton.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.ExpenseButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.ExpenseButton.Font = new System.Drawing.Font("Bebas", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.ExpenseButton.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(30)))), ((int)(((byte)(70)))));
            this.ExpenseButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.ExpenseButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.ExpenseButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.ExpenseButton.IconMarginLeft = 11;
            this.ExpenseButton.IconPadding = 10;
            this.ExpenseButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.ExpenseButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.ExpenseButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.ExpenseButton.IconSize = 25;
            this.ExpenseButton.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(248)))), ((int)(((byte)(232)))));
            this.ExpenseButton.IdleBorderRadius = 15;
            this.ExpenseButton.IdleBorderThickness = 1;
            this.ExpenseButton.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(105)))), ((int)(((byte)(105)))));
            this.ExpenseButton.IdleIconLeftImage = null;
            this.ExpenseButton.IdleIconRightImage = null;
            this.ExpenseButton.IndicateFocus = true;
            this.ExpenseButton.Location = new System.Drawing.Point(23, 505);
            this.ExpenseButton.Name = "ExpenseButton";
            this.ExpenseButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.ExpenseButton.OnDisabledState.BorderRadius = 15;
            this.ExpenseButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ExpenseButton.OnDisabledState.BorderThickness = 1;
            this.ExpenseButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ExpenseButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.ExpenseButton.OnDisabledState.IconLeftImage = null;
            this.ExpenseButton.OnDisabledState.IconRightImage = null;
            this.ExpenseButton.onHoverState.BorderColor = System.Drawing.Color.White;
            this.ExpenseButton.onHoverState.BorderRadius = 15;
            this.ExpenseButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.ExpenseButton.onHoverState.BorderThickness = 1;
            this.ExpenseButton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(199)))), ((int)(((byte)(0)))), ((int)(((byte)(57)))));
            this.ExpenseButton.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(30)))), ((int)(((byte)(70)))));
            this.ExpenseButton.onHoverState.IconLeftImage = null;
            this.ExpenseButton.onHoverState.IconRightImage = null;
            this.ExpenseButton.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(248)))), ((int)(((byte)(232)))));
            this.ExpenseButton.OnIdleState.BorderRadius = 15;
            this.ExpenseButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.ExpenseButton.OnIdleState.BorderThickness = 1;
            this.ExpenseButton.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(105)))), ((int)(((byte)(105)))));
            this.ExpenseButton.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(30)))), ((int)(((byte)(70)))));
            this.ExpenseButton.OnIdleState.IconLeftImage = null;
            this.ExpenseButton.OnIdleState.IconRightImage = null;
            this.ExpenseButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.ExpenseButton.OnPressedState.BorderRadius = 15;
            this.ExpenseButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ExpenseButton.OnPressedState.BorderThickness = 1;
            this.ExpenseButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.ExpenseButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.ExpenseButton.OnPressedState.IconLeftImage = null;
            this.ExpenseButton.OnPressedState.IconRightImage = null;
            this.ExpenseButton.Size = new System.Drawing.Size(182, 39);
            this.ExpenseButton.TabIndex = 3;
            this.ExpenseButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.ExpenseButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.ExpenseButton.TextMarginLeft = 0;
            this.ExpenseButton.TextPadding = new System.Windows.Forms.Padding(0);
            this.ExpenseButton.UseDefaultRadiusAndThickness = true;
            this.ExpenseButton.Click += new System.EventHandler(this.ExpenseButton_Click);
            // 
            // UsersButton
            // 
            this.UsersButton.AllowAnimations = true;
            this.UsersButton.AllowMouseEffects = true;
            this.UsersButton.AllowToggling = false;
            this.UsersButton.AnimationSpeed = 200;
            this.UsersButton.AutoGenerateColors = false;
            this.UsersButton.AutoRoundBorders = false;
            this.UsersButton.AutoSizeLeftIcon = true;
            this.UsersButton.AutoSizeRightIcon = true;
            this.UsersButton.BackColor = System.Drawing.Color.Transparent;
            this.UsersButton.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(105)))), ((int)(((byte)(105)))));
            this.UsersButton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("UsersButton.BackgroundImage")));
            this.UsersButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.UsersButton.ButtonText = "Users";
            this.UsersButton.ButtonTextMarginLeft = 0;
            this.UsersButton.ColorContrastOnClick = 45;
            this.UsersButton.ColorContrastOnHover = 45;
            this.UsersButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.UsersButton.CustomizableEdges = borderEdges5;
            this.UsersButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.UsersButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.UsersButton.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.UsersButton.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.UsersButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.UsersButton.Font = new System.Drawing.Font("Bebas", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.UsersButton.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(30)))), ((int)(((byte)(70)))));
            this.UsersButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.UsersButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.UsersButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.UsersButton.IconMarginLeft = 11;
            this.UsersButton.IconPadding = 10;
            this.UsersButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.UsersButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.UsersButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.UsersButton.IconSize = 25;
            this.UsersButton.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(248)))), ((int)(((byte)(232)))));
            this.UsersButton.IdleBorderRadius = 15;
            this.UsersButton.IdleBorderThickness = 1;
            this.UsersButton.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(105)))), ((int)(((byte)(105)))));
            this.UsersButton.IdleIconLeftImage = null;
            this.UsersButton.IdleIconRightImage = null;
            this.UsersButton.IndicateFocus = true;
            this.UsersButton.Location = new System.Drawing.Point(23, 617);
            this.UsersButton.Name = "UsersButton";
            this.UsersButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.UsersButton.OnDisabledState.BorderRadius = 15;
            this.UsersButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.UsersButton.OnDisabledState.BorderThickness = 1;
            this.UsersButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.UsersButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.UsersButton.OnDisabledState.IconLeftImage = null;
            this.UsersButton.OnDisabledState.IconRightImage = null;
            this.UsersButton.onHoverState.BorderColor = System.Drawing.Color.White;
            this.UsersButton.onHoverState.BorderRadius = 15;
            this.UsersButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.UsersButton.onHoverState.BorderThickness = 1;
            this.UsersButton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(199)))), ((int)(((byte)(0)))), ((int)(((byte)(57)))));
            this.UsersButton.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(30)))), ((int)(((byte)(70)))));
            this.UsersButton.onHoverState.IconLeftImage = null;
            this.UsersButton.onHoverState.IconRightImage = null;
            this.UsersButton.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(248)))), ((int)(((byte)(232)))));
            this.UsersButton.OnIdleState.BorderRadius = 15;
            this.UsersButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.UsersButton.OnIdleState.BorderThickness = 1;
            this.UsersButton.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(105)))), ((int)(((byte)(105)))));
            this.UsersButton.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(30)))), ((int)(((byte)(70)))));
            this.UsersButton.OnIdleState.IconLeftImage = null;
            this.UsersButton.OnIdleState.IconRightImage = null;
            this.UsersButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.UsersButton.OnPressedState.BorderRadius = 15;
            this.UsersButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.UsersButton.OnPressedState.BorderThickness = 1;
            this.UsersButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.UsersButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.UsersButton.OnPressedState.IconLeftImage = null;
            this.UsersButton.OnPressedState.IconRightImage = null;
            this.UsersButton.Size = new System.Drawing.Size(182, 39);
            this.UsersButton.TabIndex = 4;
            this.UsersButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.UsersButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.UsersButton.TextMarginLeft = 0;
            this.UsersButton.TextPadding = new System.Windows.Forms.Padding(0);
            this.UsersButton.UseDefaultRadiusAndThickness = true;
            this.UsersButton.Click += new System.EventHandler(this.UsersButton_Click);
            // 
            // IncomeButton
            // 
            this.IncomeButton.AllowAnimations = true;
            this.IncomeButton.AllowMouseEffects = true;
            this.IncomeButton.AllowToggling = false;
            this.IncomeButton.AnimationSpeed = 200;
            this.IncomeButton.AutoGenerateColors = false;
            this.IncomeButton.AutoRoundBorders = false;
            this.IncomeButton.AutoSizeLeftIcon = true;
            this.IncomeButton.AutoSizeRightIcon = true;
            this.IncomeButton.BackColor = System.Drawing.Color.Transparent;
            this.IncomeButton.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(105)))), ((int)(((byte)(105)))));
            this.IncomeButton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("IncomeButton.BackgroundImage")));
            this.IncomeButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.IncomeButton.ButtonText = "Manage Income";
            this.IncomeButton.ButtonTextMarginLeft = 0;
            this.IncomeButton.ColorContrastOnClick = 45;
            this.IncomeButton.ColorContrastOnHover = 45;
            this.IncomeButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.IncomeButton.CustomizableEdges = borderEdges6;
            this.IncomeButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.IncomeButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.IncomeButton.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.IncomeButton.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.IncomeButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.IncomeButton.Font = new System.Drawing.Font("Bebas", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.IncomeButton.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(30)))), ((int)(((byte)(70)))));
            this.IncomeButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.IncomeButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.IncomeButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.IncomeButton.IconMarginLeft = 11;
            this.IncomeButton.IconPadding = 10;
            this.IncomeButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.IncomeButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.IncomeButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.IncomeButton.IconSize = 25;
            this.IncomeButton.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(248)))), ((int)(((byte)(232)))));
            this.IncomeButton.IdleBorderRadius = 15;
            this.IncomeButton.IdleBorderThickness = 1;
            this.IncomeButton.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(105)))), ((int)(((byte)(105)))));
            this.IncomeButton.IdleIconLeftImage = null;
            this.IncomeButton.IdleIconRightImage = null;
            this.IncomeButton.IndicateFocus = true;
            this.IncomeButton.Location = new System.Drawing.Point(23, 563);
            this.IncomeButton.Name = "IncomeButton";
            this.IncomeButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.IncomeButton.OnDisabledState.BorderRadius = 15;
            this.IncomeButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.IncomeButton.OnDisabledState.BorderThickness = 1;
            this.IncomeButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.IncomeButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.IncomeButton.OnDisabledState.IconLeftImage = null;
            this.IncomeButton.OnDisabledState.IconRightImage = null;
            this.IncomeButton.onHoverState.BorderColor = System.Drawing.Color.White;
            this.IncomeButton.onHoverState.BorderRadius = 15;
            this.IncomeButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.IncomeButton.onHoverState.BorderThickness = 1;
            this.IncomeButton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(199)))), ((int)(((byte)(0)))), ((int)(((byte)(57)))));
            this.IncomeButton.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(30)))), ((int)(((byte)(70)))));
            this.IncomeButton.onHoverState.IconLeftImage = null;
            this.IncomeButton.onHoverState.IconRightImage = null;
            this.IncomeButton.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(248)))), ((int)(((byte)(232)))));
            this.IncomeButton.OnIdleState.BorderRadius = 15;
            this.IncomeButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.IncomeButton.OnIdleState.BorderThickness = 1;
            this.IncomeButton.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(105)))), ((int)(((byte)(105)))));
            this.IncomeButton.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(30)))), ((int)(((byte)(70)))));
            this.IncomeButton.OnIdleState.IconLeftImage = null;
            this.IncomeButton.OnIdleState.IconRightImage = null;
            this.IncomeButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.IncomeButton.OnPressedState.BorderRadius = 15;
            this.IncomeButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.IncomeButton.OnPressedState.BorderThickness = 1;
            this.IncomeButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.IncomeButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.IncomeButton.OnPressedState.IconLeftImage = null;
            this.IncomeButton.OnPressedState.IconRightImage = null;
            this.IncomeButton.Size = new System.Drawing.Size(182, 39);
            this.IncomeButton.TabIndex = 6;
            this.IncomeButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.IncomeButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.IncomeButton.TextMarginLeft = 0;
            this.IncomeButton.TextPadding = new System.Windows.Forms.Padding(0);
            this.IncomeButton.UseDefaultRadiusAndThickness = true;
            this.IncomeButton.Click += new System.EventHandler(this.IncomeButton_Click);
            // 
            // RenewButton
            // 
            this.RenewButton.AllowAnimations = true;
            this.RenewButton.AllowMouseEffects = true;
            this.RenewButton.AllowToggling = false;
            this.RenewButton.AnimationSpeed = 200;
            this.RenewButton.AutoGenerateColors = false;
            this.RenewButton.AutoRoundBorders = false;
            this.RenewButton.AutoSizeLeftIcon = true;
            this.RenewButton.AutoSizeRightIcon = true;
            this.RenewButton.BackColor = System.Drawing.Color.Transparent;
            this.RenewButton.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(105)))), ((int)(((byte)(105)))));
            this.RenewButton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("RenewButton.BackgroundImage")));
            this.RenewButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.RenewButton.ButtonText = "Renew";
            this.RenewButton.ButtonTextMarginLeft = 0;
            this.RenewButton.ColorContrastOnClick = 45;
            this.RenewButton.ColorContrastOnHover = 45;
            this.RenewButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.RenewButton.CustomizableEdges = borderEdges7;
            this.RenewButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.RenewButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.RenewButton.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.RenewButton.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.RenewButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.RenewButton.Font = new System.Drawing.Font("Bebas", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.RenewButton.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(30)))), ((int)(((byte)(70)))));
            this.RenewButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.RenewButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.RenewButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.RenewButton.IconMarginLeft = 11;
            this.RenewButton.IconPadding = 10;
            this.RenewButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.RenewButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.RenewButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.RenewButton.IconSize = 25;
            this.RenewButton.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(248)))), ((int)(((byte)(232)))));
            this.RenewButton.IdleBorderRadius = 15;
            this.RenewButton.IdleBorderThickness = 1;
            this.RenewButton.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(105)))), ((int)(((byte)(105)))));
            this.RenewButton.IdleIconLeftImage = null;
            this.RenewButton.IdleIconRightImage = null;
            this.RenewButton.IndicateFocus = true;
            this.RenewButton.Location = new System.Drawing.Point(23, 395);
            this.RenewButton.Name = "RenewButton";
            this.RenewButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.RenewButton.OnDisabledState.BorderRadius = 15;
            this.RenewButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.RenewButton.OnDisabledState.BorderThickness = 1;
            this.RenewButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.RenewButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.RenewButton.OnDisabledState.IconLeftImage = null;
            this.RenewButton.OnDisabledState.IconRightImage = null;
            this.RenewButton.onHoverState.BorderColor = System.Drawing.Color.White;
            this.RenewButton.onHoverState.BorderRadius = 15;
            this.RenewButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.RenewButton.onHoverState.BorderThickness = 1;
            this.RenewButton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(199)))), ((int)(((byte)(0)))), ((int)(((byte)(57)))));
            this.RenewButton.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(30)))), ((int)(((byte)(70)))));
            this.RenewButton.onHoverState.IconLeftImage = null;
            this.RenewButton.onHoverState.IconRightImage = null;
            this.RenewButton.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(248)))), ((int)(((byte)(232)))));
            this.RenewButton.OnIdleState.BorderRadius = 15;
            this.RenewButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.RenewButton.OnIdleState.BorderThickness = 1;
            this.RenewButton.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(105)))), ((int)(((byte)(105)))));
            this.RenewButton.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(30)))), ((int)(((byte)(70)))));
            this.RenewButton.OnIdleState.IconLeftImage = null;
            this.RenewButton.OnIdleState.IconRightImage = null;
            this.RenewButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.RenewButton.OnPressedState.BorderRadius = 15;
            this.RenewButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.RenewButton.OnPressedState.BorderThickness = 1;
            this.RenewButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.RenewButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.RenewButton.OnPressedState.IconLeftImage = null;
            this.RenewButton.OnPressedState.IconRightImage = null;
            this.RenewButton.Size = new System.Drawing.Size(182, 39);
            this.RenewButton.TabIndex = 7;
            this.RenewButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.RenewButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.RenewButton.TextMarginLeft = 0;
            this.RenewButton.TextPadding = new System.Windows.Forms.Padding(0);
            this.RenewButton.UseDefaultRadiusAndThickness = true;
            this.RenewButton.Click += new System.EventHandler(this.RenewButton_Click);
            // 
            // DashboardButton
            // 
            this.DashboardButton.AllowAnimations = true;
            this.DashboardButton.AllowMouseEffects = true;
            this.DashboardButton.AllowToggling = false;
            this.DashboardButton.AnimationSpeed = 200;
            this.DashboardButton.AutoGenerateColors = false;
            this.DashboardButton.AutoRoundBorders = false;
            this.DashboardButton.AutoSizeLeftIcon = true;
            this.DashboardButton.AutoSizeRightIcon = true;
            this.DashboardButton.BackColor = System.Drawing.Color.Transparent;
            this.DashboardButton.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(105)))), ((int)(((byte)(105)))));
            this.DashboardButton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("DashboardButton.BackgroundImage")));
            this.DashboardButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.DashboardButton.ButtonText = "Dashboard";
            this.DashboardButton.ButtonTextMarginLeft = 0;
            this.DashboardButton.ColorContrastOnClick = 45;
            this.DashboardButton.ColorContrastOnHover = 45;
            this.DashboardButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.DashboardButton.CustomizableEdges = borderEdges8;
            this.DashboardButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.DashboardButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.DashboardButton.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.DashboardButton.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.DashboardButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.DashboardButton.Font = new System.Drawing.Font("Bebas", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.DashboardButton.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(30)))), ((int)(((byte)(70)))));
            this.DashboardButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.DashboardButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.DashboardButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.DashboardButton.IconMarginLeft = 11;
            this.DashboardButton.IconPadding = 10;
            this.DashboardButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.DashboardButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.DashboardButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.DashboardButton.IconSize = 25;
            this.DashboardButton.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(248)))), ((int)(((byte)(232)))));
            this.DashboardButton.IdleBorderRadius = 15;
            this.DashboardButton.IdleBorderThickness = 1;
            this.DashboardButton.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(105)))), ((int)(((byte)(105)))));
            this.DashboardButton.IdleIconLeftImage = null;
            this.DashboardButton.IdleIconRightImage = null;
            this.DashboardButton.IndicateFocus = true;
            this.DashboardButton.Location = new System.Drawing.Point(23, 229);
            this.DashboardButton.Name = "DashboardButton";
            this.DashboardButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.DashboardButton.OnDisabledState.BorderRadius = 15;
            this.DashboardButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.DashboardButton.OnDisabledState.BorderThickness = 1;
            this.DashboardButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.DashboardButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.DashboardButton.OnDisabledState.IconLeftImage = null;
            this.DashboardButton.OnDisabledState.IconRightImage = null;
            this.DashboardButton.onHoverState.BorderColor = System.Drawing.Color.White;
            this.DashboardButton.onHoverState.BorderRadius = 15;
            this.DashboardButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.DashboardButton.onHoverState.BorderThickness = 1;
            this.DashboardButton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(199)))), ((int)(((byte)(0)))), ((int)(((byte)(57)))));
            this.DashboardButton.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(30)))), ((int)(((byte)(70)))));
            this.DashboardButton.onHoverState.IconLeftImage = null;
            this.DashboardButton.onHoverState.IconRightImage = null;
            this.DashboardButton.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(248)))), ((int)(((byte)(232)))));
            this.DashboardButton.OnIdleState.BorderRadius = 15;
            this.DashboardButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.DashboardButton.OnIdleState.BorderThickness = 1;
            this.DashboardButton.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(105)))), ((int)(((byte)(105)))));
            this.DashboardButton.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(30)))), ((int)(((byte)(70)))));
            this.DashboardButton.OnIdleState.IconLeftImage = null;
            this.DashboardButton.OnIdleState.IconRightImage = null;
            this.DashboardButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.DashboardButton.OnPressedState.BorderRadius = 15;
            this.DashboardButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.DashboardButton.OnPressedState.BorderThickness = 1;
            this.DashboardButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.DashboardButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.DashboardButton.OnPressedState.IconLeftImage = null;
            this.DashboardButton.OnPressedState.IconRightImage = null;
            this.DashboardButton.Size = new System.Drawing.Size(182, 39);
            this.DashboardButton.TabIndex = 1;
            this.DashboardButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.DashboardButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.DashboardButton.TextMarginLeft = 0;
            this.DashboardButton.TextPadding = new System.Windows.Forms.Padding(0);
            this.DashboardButton.UseDefaultRadiusAndThickness = true;
            this.DashboardButton.Click += new System.EventHandler(this.DashboardButton_Click);
            // 
            // MainPanel
            // 
            this.MainPanel.BackColor = System.Drawing.Color.Transparent;
            this.MainPanel.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.MainPanel.BorderRadius = 15;
            this.MainPanel.BorderThickness = 1;
            this.MainPanel.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Solid;
            this.MainPanel.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.MainPanel.Location = new System.Drawing.Point(239, 31);
            this.MainPanel.Name = "MainPanel";
            this.MainPanel.PanelColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(245)))), ((int)(((byte)(224)))));
            this.MainPanel.PanelColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(245)))), ((int)(((byte)(224)))));
            this.MainPanel.ShadowColor = System.Drawing.Color.DarkGray;
            this.MainPanel.ShadowDept = 2;
            this.MainPanel.ShadowDepth = 4;
            this.MainPanel.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Surrounded;
            this.MainPanel.ShadowTopLeftVisible = false;
            this.MainPanel.Size = new System.Drawing.Size(790, 700);
            this.MainPanel.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.MainPanel.TabIndex = 1;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.Font = new System.Drawing.Font("Bebas", 15.75F);
            this.bunifuLabel2.Location = new System.Drawing.Point(248, 1);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(294, 25);
            this.bunifuLabel2.TabIndex = 19;
            this.bunifuLabel2.Text = "Gym Matrix - Gym Management System";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // MinimizeAppButton
            // 
            this.MinimizeAppButton.ActiveImage = null;
            this.MinimizeAppButton.AllowAnimations = true;
            this.MinimizeAppButton.AllowBuffering = false;
            this.MinimizeAppButton.AllowToggling = false;
            this.MinimizeAppButton.AllowZooming = true;
            this.MinimizeAppButton.AllowZoomingOnFocus = false;
            this.MinimizeAppButton.BackColor = System.Drawing.Color.Transparent;
            this.MinimizeAppButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.MinimizeAppButton.ErrorImage = ((System.Drawing.Image)(resources.GetObject("MinimizeAppButton.ErrorImage")));
            this.MinimizeAppButton.FadeWhenInactive = false;
            this.MinimizeAppButton.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.MinimizeAppButton.Image = global::Matrix.Properties.Resources.Minimize;
            this.MinimizeAppButton.ImageActive = null;
            this.MinimizeAppButton.ImageLocation = null;
            this.MinimizeAppButton.ImageMargin = 0;
            this.MinimizeAppButton.ImageSize = new System.Drawing.Size(29, 29);
            this.MinimizeAppButton.ImageZoomSize = new System.Drawing.Size(30, 30);
            this.MinimizeAppButton.InitialImage = ((System.Drawing.Image)(resources.GetObject("MinimizeAppButton.InitialImage")));
            this.MinimizeAppButton.Location = new System.Drawing.Point(964, 3);
            this.MinimizeAppButton.Name = "MinimizeAppButton";
            this.MinimizeAppButton.Rotation = 0;
            this.MinimizeAppButton.ShowActiveImage = true;
            this.MinimizeAppButton.ShowCursorChanges = true;
            this.MinimizeAppButton.ShowImageBorders = true;
            this.MinimizeAppButton.ShowSizeMarkers = false;
            this.MinimizeAppButton.Size = new System.Drawing.Size(30, 30);
            this.MinimizeAppButton.TabIndex = 4;
            this.MinimizeAppButton.ToolTipText = "";
            this.MinimizeAppButton.WaitOnLoad = false;
            this.MinimizeAppButton.Zoom = 0;
            this.MinimizeAppButton.ZoomSpeed = 10;
            this.MinimizeAppButton.Click += new System.EventHandler(this.MinimizeAppButton_Click);
            // 
            // CloseButton
            // 
            this.CloseButton.ActiveImage = null;
            this.CloseButton.AllowAnimations = true;
            this.CloseButton.AllowBuffering = false;
            this.CloseButton.AllowToggling = false;
            this.CloseButton.AllowZooming = true;
            this.CloseButton.AllowZoomingOnFocus = false;
            this.CloseButton.BackColor = System.Drawing.Color.Transparent;
            this.CloseButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.CloseButton.ErrorImage = ((System.Drawing.Image)(resources.GetObject("CloseButton.ErrorImage")));
            this.CloseButton.FadeWhenInactive = false;
            this.CloseButton.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.CloseButton.Image = global::Matrix.Properties.Resources.Close;
            this.CloseButton.ImageActive = null;
            this.CloseButton.ImageLocation = null;
            this.CloseButton.ImageMargin = 0;
            this.CloseButton.ImageSize = new System.Drawing.Size(29, 29);
            this.CloseButton.ImageZoomSize = new System.Drawing.Size(30, 30);
            this.CloseButton.InitialImage = ((System.Drawing.Image)(resources.GetObject("CloseButton.InitialImage")));
            this.CloseButton.Location = new System.Drawing.Point(995, 3);
            this.CloseButton.Name = "CloseButton";
            this.CloseButton.Rotation = 0;
            this.CloseButton.ShowActiveImage = true;
            this.CloseButton.ShowCursorChanges = true;
            this.CloseButton.ShowImageBorders = true;
            this.CloseButton.ShowSizeMarkers = false;
            this.CloseButton.Size = new System.Drawing.Size(30, 30);
            this.CloseButton.TabIndex = 5;
            this.CloseButton.ToolTipText = "";
            this.CloseButton.WaitOnLoad = false;
            this.CloseButton.Zoom = 0;
            this.CloseButton.ZoomSpeed = 10;
            this.CloseButton.Click += new System.EventHandler(this.CloseButton_Click);
            // 
            // Update
            // 
            this.Update.AllowAnimations = true;
            this.Update.AllowMouseEffects = true;
            this.Update.AllowToggling = false;
            this.Update.AnimationSpeed = 200;
            this.Update.AutoGenerateColors = false;
            this.Update.AutoRoundBorders = false;
            this.Update.AutoSizeLeftIcon = true;
            this.Update.AutoSizeRightIcon = true;
            this.Update.BackColor = System.Drawing.Color.Transparent;
            this.Update.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(105)))), ((int)(((byte)(105)))));
            this.Update.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Update.BackgroundImage")));
            this.Update.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.Update.ButtonText = "Update";
            this.Update.ButtonTextMarginLeft = 0;
            this.Update.ColorContrastOnClick = 45;
            this.Update.ColorContrastOnHover = 45;
            this.Update.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.Update.CustomizableEdges = borderEdges1;
            this.Update.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Update.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Update.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Update.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Update.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.Update.Font = new System.Drawing.Font("Bebas", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Update.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(30)))), ((int)(((byte)(70)))));
            this.Update.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Update.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Update.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Update.IconMarginLeft = 11;
            this.Update.IconPadding = 10;
            this.Update.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Update.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Update.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Update.IconSize = 25;
            this.Update.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(248)))), ((int)(((byte)(232)))));
            this.Update.IdleBorderRadius = 15;
            this.Update.IdleBorderThickness = 1;
            this.Update.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(105)))), ((int)(((byte)(105)))));
            this.Update.IdleIconLeftImage = null;
            this.Update.IdleIconRightImage = null;
            this.Update.IndicateFocus = true;
            this.Update.Location = new System.Drawing.Point(24, 339);
            this.Update.Name = "Update";
            this.Update.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Update.OnDisabledState.BorderRadius = 15;
            this.Update.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Update.OnDisabledState.BorderThickness = 1;
            this.Update.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Update.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Update.OnDisabledState.IconLeftImage = null;
            this.Update.OnDisabledState.IconRightImage = null;
            this.Update.onHoverState.BorderColor = System.Drawing.Color.White;
            this.Update.onHoverState.BorderRadius = 15;
            this.Update.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.Update.onHoverState.BorderThickness = 1;
            this.Update.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(199)))), ((int)(((byte)(0)))), ((int)(((byte)(57)))));
            this.Update.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(30)))), ((int)(((byte)(70)))));
            this.Update.onHoverState.IconLeftImage = null;
            this.Update.onHoverState.IconRightImage = null;
            this.Update.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(248)))), ((int)(((byte)(232)))));
            this.Update.OnIdleState.BorderRadius = 15;
            this.Update.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.Update.OnIdleState.BorderThickness = 1;
            this.Update.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(105)))), ((int)(((byte)(105)))));
            this.Update.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(30)))), ((int)(((byte)(70)))));
            this.Update.OnIdleState.IconLeftImage = null;
            this.Update.OnIdleState.IconRightImage = null;
            this.Update.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Update.OnPressedState.BorderRadius = 15;
            this.Update.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Update.OnPressedState.BorderThickness = 1;
            this.Update.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Update.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.Update.OnPressedState.IconLeftImage = null;
            this.Update.OnPressedState.IconRightImage = null;
            this.Update.Size = new System.Drawing.Size(182, 39);
            this.Update.TabIndex = 21;
            this.Update.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Update.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Update.TextMarginLeft = 0;
            this.Update.TextPadding = new System.Windows.Forms.Padding(0);
            this.Update.UseDefaultRadiusAndThickness = true;
            this.Update.Click += new System.EventHandler(this.Update_Click);
            // 
            // MainForm
            // 
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(1037, 751);
            this.Controls.Add(this.bunifuLabel2);
            this.Controls.Add(this.MinimizeAppButton);
            this.Controls.Add(this.CloseButton);
            this.Controls.Add(this.MainPanel);
            this.Controls.Add(this.bunifuShadowPanel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Name = "MainForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "GMS";
            this.Load += new System.EventHandler(this.MainForm_Load);
            this.bunifuShadowPanel1.ResumeLayout(false);
            this.bunifuShadowPanel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.Framework.UI.BunifuElipse bunifuElipse1;
        private Bunifu.UI.WinForms.BunifuShadowPanel bunifuShadowPanel1;
        private Bunifu.UI.WinForms.BunifuShadowPanel MainPanel;
        private Bunifu.UI.WinForms.BunifuImageButton MinimizeAppButton;
        private Bunifu.UI.WinForms.BunifuImageButton CloseButton;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton MembersButton;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton ExpenseButton;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton UsersButton;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton IncomeButton;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton RenewButton;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton DashboardButton;
        private System.Windows.Forms.PictureBox pictureBox1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton PaymentButton;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Update;
    }
}

