namespace Matrix
{
    partial class Users
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle4 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle5 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle6 = new System.Windows.Forms.DataGridViewCellStyle();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Users));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.bunifuShadowPanel6 = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel6 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuElipse1 = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.CustomersDataGridView = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.AddButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.ClearButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.RemoveButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.UpdateButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.ConfirmBox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.PassBox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.UsernameBox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuShadowPanel6.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.CustomersDataGridView)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuShadowPanel6
            // 
            this.bunifuShadowPanel6.BackColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel6.BorderColor = System.Drawing.Color.Gray;
            this.bunifuShadowPanel6.BorderRadius = 10;
            this.bunifuShadowPanel6.BorderThickness = 1;
            this.bunifuShadowPanel6.Controls.Add(this.AddButton);
            this.bunifuShadowPanel6.Controls.Add(this.ClearButton);
            this.bunifuShadowPanel6.Controls.Add(this.RemoveButton);
            this.bunifuShadowPanel6.Controls.Add(this.UpdateButton);
            this.bunifuShadowPanel6.Controls.Add(this.ConfirmBox);
            this.bunifuShadowPanel6.Controls.Add(this.bunifuLabel3);
            this.bunifuShadowPanel6.Controls.Add(this.PassBox);
            this.bunifuShadowPanel6.Controls.Add(this.bunifuLabel2);
            this.bunifuShadowPanel6.Controls.Add(this.UsernameBox);
            this.bunifuShadowPanel6.Controls.Add(this.bunifuLabel6);
            this.bunifuShadowPanel6.Controls.Add(this.bunifuLabel1);
            this.bunifuShadowPanel6.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Solid;
            this.bunifuShadowPanel6.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.bunifuShadowPanel6.Location = new System.Drawing.Point(7, 10);
            this.bunifuShadowPanel6.Name = "bunifuShadowPanel6";
            this.bunifuShadowPanel6.PanelColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(239)))), ((int)(((byte)(234)))));
            this.bunifuShadowPanel6.PanelColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(239)))), ((int)(((byte)(234)))));
            this.bunifuShadowPanel6.ShadowColor = System.Drawing.Color.DarkGray;
            this.bunifuShadowPanel6.ShadowDept = 2;
            this.bunifuShadowPanel6.ShadowDepth = 4;
            this.bunifuShadowPanel6.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Surrounded;
            this.bunifuShadowPanel6.ShadowTopLeftVisible = false;
            this.bunifuShadowPanel6.Size = new System.Drawing.Size(771, 244);
            this.bunifuShadowPanel6.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.bunifuShadowPanel6.TabIndex = 4;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.CursorType = null;
            this.bunifuLabel3.Font = new System.Drawing.Font("Sans Serif Collection", 8.25F);
            this.bunifuLabel3.Location = new System.Drawing.Point(20, 150);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(147, 27);
            this.bunifuLabel3.TabIndex = 0;
            this.bunifuLabel3.TabStop = false;
            this.bunifuLabel3.Text = "Confirm Password:";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.CursorType = null;
            this.bunifuLabel2.Font = new System.Drawing.Font("Sans Serif Collection", 8.25F);
            this.bunifuLabel2.Location = new System.Drawing.Point(20, 107);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(82, 27);
            this.bunifuLabel2.TabIndex = 0;
            this.bunifuLabel2.TabStop = false;
            this.bunifuLabel2.Text = "Password:";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel6
            // 
            this.bunifuLabel6.AllowParentOverrides = false;
            this.bunifuLabel6.AutoEllipsis = false;
            this.bunifuLabel6.CursorType = null;
            this.bunifuLabel6.Font = new System.Drawing.Font("Bebas", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel6.Location = new System.Drawing.Point(20, 16);
            this.bunifuLabel6.Name = "bunifuLabel6";
            this.bunifuLabel6.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel6.Size = new System.Drawing.Size(86, 29);
            this.bunifuLabel6.TabIndex = 0;
            this.bunifuLabel6.TabStop = false;
            this.bunifuLabel6.Text = "Add Users";
            this.bunifuLabel6.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel6.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.CursorType = null;
            this.bunifuLabel1.Font = new System.Drawing.Font("Sans Serif Collection", 8.25F);
            this.bunifuLabel1.Location = new System.Drawing.Point(20, 63);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(85, 27);
            this.bunifuLabel1.TabIndex = 0;
            this.bunifuLabel1.TabStop = false;
            this.bunifuLabel1.Text = "Username:";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuElipse1
            // 
            this.bunifuElipse1.ElipseRadius = 20;
            this.bunifuElipse1.TargetControl = this;
            // 
            // CustomersDataGridView
            // 
            this.CustomersDataGridView.AllowCustomTheming = false;
            this.CustomersDataGridView.AllowUserToAddRows = false;
            this.CustomersDataGridView.AllowUserToDeleteRows = false;
            dataGridViewCellStyle4.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(196)))), ((int)(((byte)(206)))));
            dataGridViewCellStyle4.ForeColor = System.Drawing.Color.Black;
            this.CustomersDataGridView.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle4;
            this.CustomersDataGridView.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.CustomersDataGridView.BackgroundColor = System.Drawing.Color.White;
            this.CustomersDataGridView.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.CustomersDataGridView.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.Raised;
            this.CustomersDataGridView.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle5.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle5.BackColor = System.Drawing.Color.Crimson;
            dataGridViewCellStyle5.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle5.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle5.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(176)))), ((int)(((byte)(16)))), ((int)(((byte)(48)))));
            dataGridViewCellStyle5.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle5.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.CustomersDataGridView.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle5;
            this.CustomersDataGridView.ColumnHeadersHeight = 40;
            this.CustomersDataGridView.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(196)))), ((int)(((byte)(206)))));
            this.CustomersDataGridView.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.CustomersDataGridView.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.CustomersDataGridView.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(114)))), ((int)(((byte)(138)))));
            this.CustomersDataGridView.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.White;
            this.CustomersDataGridView.CurrentTheme.BackColor = System.Drawing.Color.Crimson;
            this.CustomersDataGridView.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(244)))), ((int)(((byte)(184)))), ((int)(((byte)(196)))));
            this.CustomersDataGridView.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.Crimson;
            this.CustomersDataGridView.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.CustomersDataGridView.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.CustomersDataGridView.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(176)))), ((int)(((byte)(16)))), ((int)(((byte)(48)))));
            this.CustomersDataGridView.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.CustomersDataGridView.CurrentTheme.Name = null;
            this.CustomersDataGridView.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(208)))), ((int)(((byte)(216)))));
            this.CustomersDataGridView.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.CustomersDataGridView.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.CustomersDataGridView.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(114)))), ((int)(((byte)(138)))));
            this.CustomersDataGridView.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle6.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle6.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(208)))), ((int)(((byte)(216)))));
            dataGridViewCellStyle6.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle6.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle6.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(114)))), ((int)(((byte)(138)))));
            dataGridViewCellStyle6.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle6.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.CustomersDataGridView.DefaultCellStyle = dataGridViewCellStyle6;
            this.CustomersDataGridView.EnableHeadersVisualStyles = false;
            this.CustomersDataGridView.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(244)))), ((int)(((byte)(184)))), ((int)(((byte)(196)))));
            this.CustomersDataGridView.HeaderBackColor = System.Drawing.Color.Crimson;
            this.CustomersDataGridView.HeaderBgColor = System.Drawing.Color.Empty;
            this.CustomersDataGridView.HeaderForeColor = System.Drawing.Color.White;
            this.CustomersDataGridView.Location = new System.Drawing.Point(7, 260);
            this.CustomersDataGridView.Name = "CustomersDataGridView";
            this.CustomersDataGridView.ReadOnly = true;
            this.CustomersDataGridView.RowHeadersVisible = false;
            this.CustomersDataGridView.RowTemplate.Height = 40;
            this.CustomersDataGridView.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.CustomersDataGridView.Size = new System.Drawing.Size(771, 417);
            this.CustomersDataGridView.TabIndex = 5;
            this.CustomersDataGridView.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Crimson;
            // 
            // AddButton
            // 
            this.AddButton.AllowAnimations = true;
            this.AddButton.AllowMouseEffects = true;
            this.AddButton.AllowToggling = false;
            this.AddButton.AnimationSpeed = 200;
            this.AddButton.AutoGenerateColors = false;
            this.AddButton.AutoRoundBorders = false;
            this.AddButton.AutoSizeLeftIcon = true;
            this.AddButton.AutoSizeRightIcon = true;
            this.AddButton.BackColor = System.Drawing.Color.Transparent;
            this.AddButton.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.AddButton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AddButton.BackgroundImage")));
            this.AddButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AddButton.ButtonText = "Add";
            this.AddButton.ButtonTextMarginLeft = 0;
            this.AddButton.ColorContrastOnClick = 45;
            this.AddButton.ColorContrastOnHover = 45;
            this.AddButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.AddButton.CustomizableEdges = borderEdges5;
            this.AddButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.AddButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AddButton.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AddButton.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AddButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.AddButton.Font = new System.Drawing.Font("Bebas", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AddButton.ForeColor = System.Drawing.Color.White;
            this.AddButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AddButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.AddButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.AddButton.IconMarginLeft = 11;
            this.AddButton.IconPadding = 10;
            this.AddButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AddButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.AddButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.AddButton.IconSize = 25;
            this.AddButton.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.AddButton.IdleBorderRadius = 15;
            this.AddButton.IdleBorderThickness = 1;
            this.AddButton.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.AddButton.IdleIconLeftImage = null;
            this.AddButton.IdleIconRightImage = null;
            this.AddButton.IndicateFocus = false;
            this.AddButton.Location = new System.Drawing.Point(20, 192);
            this.AddButton.Name = "AddButton";
            this.AddButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AddButton.OnDisabledState.BorderRadius = 15;
            this.AddButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AddButton.OnDisabledState.BorderThickness = 1;
            this.AddButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AddButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AddButton.OnDisabledState.IconLeftImage = null;
            this.AddButton.OnDisabledState.IconRightImage = null;
            this.AddButton.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.AddButton.onHoverState.BorderRadius = 15;
            this.AddButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AddButton.onHoverState.BorderThickness = 1;
            this.AddButton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.AddButton.onHoverState.ForeColor = System.Drawing.Color.White;
            this.AddButton.onHoverState.IconLeftImage = null;
            this.AddButton.onHoverState.IconRightImage = null;
            this.AddButton.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.AddButton.OnIdleState.BorderRadius = 15;
            this.AddButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AddButton.OnIdleState.BorderThickness = 1;
            this.AddButton.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.AddButton.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.AddButton.OnIdleState.IconLeftImage = null;
            this.AddButton.OnIdleState.IconRightImage = null;
            this.AddButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.AddButton.OnPressedState.BorderRadius = 15;
            this.AddButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AddButton.OnPressedState.BorderThickness = 1;
            this.AddButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.AddButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.AddButton.OnPressedState.IconLeftImage = null;
            this.AddButton.OnPressedState.IconRightImage = null;
            this.AddButton.Size = new System.Drawing.Size(142, 39);
            this.AddButton.TabIndex = 6;
            this.AddButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.AddButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.AddButton.TextMarginLeft = 0;
            this.AddButton.TextPadding = new System.Windows.Forms.Padding(0);
            this.AddButton.UseDefaultRadiusAndThickness = true;
            // 
            // ClearButton
            // 
            this.ClearButton.AllowAnimations = true;
            this.ClearButton.AllowMouseEffects = true;
            this.ClearButton.AllowToggling = false;
            this.ClearButton.AnimationSpeed = 200;
            this.ClearButton.AutoGenerateColors = false;
            this.ClearButton.AutoRoundBorders = false;
            this.ClearButton.AutoSizeLeftIcon = true;
            this.ClearButton.AutoSizeRightIcon = true;
            this.ClearButton.BackColor = System.Drawing.Color.Transparent;
            this.ClearButton.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(147)))), ((int)(((byte)(124)))));
            this.ClearButton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ClearButton.BackgroundImage")));
            this.ClearButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ClearButton.ButtonText = "Clear";
            this.ClearButton.ButtonTextMarginLeft = 0;
            this.ClearButton.ColorContrastOnClick = 45;
            this.ClearButton.ColorContrastOnHover = 45;
            this.ClearButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.ClearButton.CustomizableEdges = borderEdges6;
            this.ClearButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.ClearButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.ClearButton.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ClearButton.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.ClearButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.ClearButton.Font = new System.Drawing.Font("Bebas", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.ClearButton.ForeColor = System.Drawing.Color.White;
            this.ClearButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.ClearButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.ClearButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.ClearButton.IconMarginLeft = 11;
            this.ClearButton.IconPadding = 10;
            this.ClearButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.ClearButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.ClearButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.ClearButton.IconSize = 25;
            this.ClearButton.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(147)))), ((int)(((byte)(124)))));
            this.ClearButton.IdleBorderRadius = 15;
            this.ClearButton.IdleBorderThickness = 1;
            this.ClearButton.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(147)))), ((int)(((byte)(124)))));
            this.ClearButton.IdleIconLeftImage = null;
            this.ClearButton.IdleIconRightImage = null;
            this.ClearButton.IndicateFocus = false;
            this.ClearButton.Location = new System.Drawing.Point(531, 192);
            this.ClearButton.Name = "ClearButton";
            this.ClearButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.ClearButton.OnDisabledState.BorderRadius = 15;
            this.ClearButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ClearButton.OnDisabledState.BorderThickness = 1;
            this.ClearButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ClearButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.ClearButton.OnDisabledState.IconLeftImage = null;
            this.ClearButton.OnDisabledState.IconRightImage = null;
            this.ClearButton.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.ClearButton.onHoverState.BorderRadius = 15;
            this.ClearButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ClearButton.onHoverState.BorderThickness = 1;
            this.ClearButton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.ClearButton.onHoverState.ForeColor = System.Drawing.Color.White;
            this.ClearButton.onHoverState.IconLeftImage = null;
            this.ClearButton.onHoverState.IconRightImage = null;
            this.ClearButton.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(147)))), ((int)(((byte)(124)))));
            this.ClearButton.OnIdleState.BorderRadius = 15;
            this.ClearButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ClearButton.OnIdleState.BorderThickness = 1;
            this.ClearButton.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(147)))), ((int)(((byte)(124)))));
            this.ClearButton.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.ClearButton.OnIdleState.IconLeftImage = null;
            this.ClearButton.OnIdleState.IconRightImage = null;
            this.ClearButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.ClearButton.OnPressedState.BorderRadius = 15;
            this.ClearButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ClearButton.OnPressedState.BorderThickness = 1;
            this.ClearButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.ClearButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.ClearButton.OnPressedState.IconLeftImage = null;
            this.ClearButton.OnPressedState.IconRightImage = null;
            this.ClearButton.Size = new System.Drawing.Size(142, 39);
            this.ClearButton.TabIndex = 8;
            this.ClearButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.ClearButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.ClearButton.TextMarginLeft = 0;
            this.ClearButton.TextPadding = new System.Windows.Forms.Padding(0);
            this.ClearButton.UseDefaultRadiusAndThickness = true;
            // 
            // RemoveButton
            // 
            this.RemoveButton.AllowAnimations = true;
            this.RemoveButton.AllowMouseEffects = true;
            this.RemoveButton.AllowToggling = false;
            this.RemoveButton.AnimationSpeed = 200;
            this.RemoveButton.AutoGenerateColors = false;
            this.RemoveButton.AutoRoundBorders = false;
            this.RemoveButton.AutoSizeLeftIcon = true;
            this.RemoveButton.AutoSizeRightIcon = true;
            this.RemoveButton.BackColor = System.Drawing.Color.Transparent;
            this.RemoveButton.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(11)))), ((int)(((byte)(11)))));
            this.RemoveButton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("RemoveButton.BackgroundImage")));
            this.RemoveButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.RemoveButton.ButtonText = "Remove";
            this.RemoveButton.ButtonTextMarginLeft = 0;
            this.RemoveButton.ColorContrastOnClick = 45;
            this.RemoveButton.ColorContrastOnHover = 45;
            this.RemoveButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.RemoveButton.CustomizableEdges = borderEdges7;
            this.RemoveButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.RemoveButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.RemoveButton.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.RemoveButton.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.RemoveButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.RemoveButton.Font = new System.Drawing.Font("Bebas", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.RemoveButton.ForeColor = System.Drawing.Color.White;
            this.RemoveButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.RemoveButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.RemoveButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.RemoveButton.IconMarginLeft = 11;
            this.RemoveButton.IconPadding = 10;
            this.RemoveButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.RemoveButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.RemoveButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.RemoveButton.IconSize = 25;
            this.RemoveButton.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(11)))), ((int)(((byte)(11)))));
            this.RemoveButton.IdleBorderRadius = 15;
            this.RemoveButton.IdleBorderThickness = 1;
            this.RemoveButton.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(11)))), ((int)(((byte)(11)))));
            this.RemoveButton.IdleIconLeftImage = null;
            this.RemoveButton.IdleIconRightImage = null;
            this.RemoveButton.IndicateFocus = false;
            this.RemoveButton.Location = new System.Drawing.Point(354, 192);
            this.RemoveButton.Name = "RemoveButton";
            this.RemoveButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.RemoveButton.OnDisabledState.BorderRadius = 15;
            this.RemoveButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.RemoveButton.OnDisabledState.BorderThickness = 1;
            this.RemoveButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.RemoveButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.RemoveButton.OnDisabledState.IconLeftImage = null;
            this.RemoveButton.OnDisabledState.IconRightImage = null;
            this.RemoveButton.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.RemoveButton.onHoverState.BorderRadius = 15;
            this.RemoveButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.RemoveButton.onHoverState.BorderThickness = 1;
            this.RemoveButton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.RemoveButton.onHoverState.ForeColor = System.Drawing.Color.White;
            this.RemoveButton.onHoverState.IconLeftImage = null;
            this.RemoveButton.onHoverState.IconRightImage = null;
            this.RemoveButton.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(11)))), ((int)(((byte)(11)))));
            this.RemoveButton.OnIdleState.BorderRadius = 15;
            this.RemoveButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.RemoveButton.OnIdleState.BorderThickness = 1;
            this.RemoveButton.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(11)))), ((int)(((byte)(11)))));
            this.RemoveButton.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.RemoveButton.OnIdleState.IconLeftImage = null;
            this.RemoveButton.OnIdleState.IconRightImage = null;
            this.RemoveButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.RemoveButton.OnPressedState.BorderRadius = 15;
            this.RemoveButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.RemoveButton.OnPressedState.BorderThickness = 1;
            this.RemoveButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.RemoveButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.RemoveButton.OnPressedState.IconLeftImage = null;
            this.RemoveButton.OnPressedState.IconRightImage = null;
            this.RemoveButton.Size = new System.Drawing.Size(142, 39);
            this.RemoveButton.TabIndex = 8;
            this.RemoveButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.RemoveButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.RemoveButton.TextMarginLeft = 0;
            this.RemoveButton.TextPadding = new System.Windows.Forms.Padding(0);
            this.RemoveButton.UseDefaultRadiusAndThickness = true;
            // 
            // UpdateButton
            // 
            this.UpdateButton.AllowAnimations = true;
            this.UpdateButton.AllowMouseEffects = true;
            this.UpdateButton.AllowToggling = false;
            this.UpdateButton.AnimationSpeed = 200;
            this.UpdateButton.AutoGenerateColors = false;
            this.UpdateButton.AutoRoundBorders = false;
            this.UpdateButton.AutoSizeLeftIcon = true;
            this.UpdateButton.AutoSizeRightIcon = true;
            this.UpdateButton.BackColor = System.Drawing.Color.Transparent;
            this.UpdateButton.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(98)))), ((int)(((byte)(0)))));
            this.UpdateButton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("UpdateButton.BackgroundImage")));
            this.UpdateButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.UpdateButton.ButtonText = "Update";
            this.UpdateButton.ButtonTextMarginLeft = 0;
            this.UpdateButton.ColorContrastOnClick = 45;
            this.UpdateButton.ColorContrastOnHover = 45;
            this.UpdateButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.UpdateButton.CustomizableEdges = borderEdges8;
            this.UpdateButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.UpdateButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.UpdateButton.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.UpdateButton.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.UpdateButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.UpdateButton.Font = new System.Drawing.Font("Bebas", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.UpdateButton.ForeColor = System.Drawing.Color.White;
            this.UpdateButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.UpdateButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.UpdateButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.UpdateButton.IconMarginLeft = 11;
            this.UpdateButton.IconPadding = 10;
            this.UpdateButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.UpdateButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.UpdateButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.UpdateButton.IconSize = 25;
            this.UpdateButton.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(98)))), ((int)(((byte)(0)))));
            this.UpdateButton.IdleBorderRadius = 15;
            this.UpdateButton.IdleBorderThickness = 1;
            this.UpdateButton.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(98)))), ((int)(((byte)(0)))));
            this.UpdateButton.IdleIconLeftImage = null;
            this.UpdateButton.IdleIconRightImage = null;
            this.UpdateButton.IndicateFocus = false;
            this.UpdateButton.Location = new System.Drawing.Point(184, 192);
            this.UpdateButton.Name = "UpdateButton";
            this.UpdateButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.UpdateButton.OnDisabledState.BorderRadius = 15;
            this.UpdateButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.UpdateButton.OnDisabledState.BorderThickness = 1;
            this.UpdateButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.UpdateButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.UpdateButton.OnDisabledState.IconLeftImage = null;
            this.UpdateButton.OnDisabledState.IconRightImage = null;
            this.UpdateButton.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.UpdateButton.onHoverState.BorderRadius = 15;
            this.UpdateButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.UpdateButton.onHoverState.BorderThickness = 1;
            this.UpdateButton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.UpdateButton.onHoverState.ForeColor = System.Drawing.Color.White;
            this.UpdateButton.onHoverState.IconLeftImage = null;
            this.UpdateButton.onHoverState.IconRightImage = null;
            this.UpdateButton.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(98)))), ((int)(((byte)(0)))));
            this.UpdateButton.OnIdleState.BorderRadius = 15;
            this.UpdateButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.UpdateButton.OnIdleState.BorderThickness = 1;
            this.UpdateButton.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(98)))), ((int)(((byte)(0)))));
            this.UpdateButton.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.UpdateButton.OnIdleState.IconLeftImage = null;
            this.UpdateButton.OnIdleState.IconRightImage = null;
            this.UpdateButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.UpdateButton.OnPressedState.BorderRadius = 15;
            this.UpdateButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.UpdateButton.OnPressedState.BorderThickness = 1;
            this.UpdateButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.UpdateButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.UpdateButton.OnPressedState.IconLeftImage = null;
            this.UpdateButton.OnPressedState.IconRightImage = null;
            this.UpdateButton.Size = new System.Drawing.Size(142, 39);
            this.UpdateButton.TabIndex = 7;
            this.UpdateButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.UpdateButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.UpdateButton.TextMarginLeft = 0;
            this.UpdateButton.TextPadding = new System.Windows.Forms.Padding(0);
            this.UpdateButton.UseDefaultRadiusAndThickness = true;
            // 
            // ConfirmBox
            // 
            this.ConfirmBox.AcceptsReturn = false;
            this.ConfirmBox.AcceptsTab = false;
            this.ConfirmBox.AnimationSpeed = 200;
            this.ConfirmBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.ConfirmBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.ConfirmBox.BackColor = System.Drawing.Color.Transparent;
            this.ConfirmBox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ConfirmBox.BackgroundImage")));
            this.ConfirmBox.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.ConfirmBox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ConfirmBox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.ConfirmBox.BorderColorIdle = System.Drawing.Color.Silver;
            this.ConfirmBox.BorderRadius = 15;
            this.ConfirmBox.BorderThickness = 1;
            this.ConfirmBox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.ConfirmBox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.ConfirmBox.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.ConfirmBox.DefaultText = "";
            this.ConfirmBox.FillColor = System.Drawing.Color.White;
            this.ConfirmBox.HideSelection = true;
            this.ConfirmBox.IconLeft = null;
            this.ConfirmBox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.ConfirmBox.IconPadding = 6;
            this.ConfirmBox.IconRight = null;
            this.ConfirmBox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.ConfirmBox.Lines = new string[0];
            this.ConfirmBox.Location = new System.Drawing.Point(175, 140);
            this.ConfirmBox.MaxLength = 32767;
            this.ConfirmBox.MinimumSize = new System.Drawing.Size(1, 1);
            this.ConfirmBox.Modified = false;
            this.ConfirmBox.Multiline = false;
            this.ConfirmBox.Name = "ConfirmBox";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ConfirmBox.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.ConfirmBox.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ConfirmBox.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ConfirmBox.OnIdleState = stateProperties16;
            this.ConfirmBox.Padding = new System.Windows.Forms.Padding(3);
            this.ConfirmBox.PasswordChar = '●';
            this.ConfirmBox.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.ConfirmBox.PlaceholderText = "Enter text";
            this.ConfirmBox.ReadOnly = false;
            this.ConfirmBox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.ConfirmBox.SelectedText = "";
            this.ConfirmBox.SelectionLength = 0;
            this.ConfirmBox.SelectionStart = 0;
            this.ConfirmBox.ShortcutsEnabled = true;
            this.ConfirmBox.Size = new System.Drawing.Size(443, 37);
            this.ConfirmBox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.ConfirmBox.TabIndex = 2;
            this.ConfirmBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.ConfirmBox.TextMarginBottom = 0;
            this.ConfirmBox.TextMarginLeft = 3;
            this.ConfirmBox.TextMarginTop = 0;
            this.ConfirmBox.TextPlaceholder = "Enter text";
            this.ConfirmBox.UseSystemPasswordChar = true;
            this.ConfirmBox.WordWrap = true;
            // 
            // PassBox
            // 
            this.PassBox.AcceptsReturn = false;
            this.PassBox.AcceptsTab = false;
            this.PassBox.AnimationSpeed = 200;
            this.PassBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.PassBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.PassBox.BackColor = System.Drawing.Color.Transparent;
            this.PassBox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("PassBox.BackgroundImage")));
            this.PassBox.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.PassBox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.PassBox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.PassBox.BorderColorIdle = System.Drawing.Color.Silver;
            this.PassBox.BorderRadius = 15;
            this.PassBox.BorderThickness = 1;
            this.PassBox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.PassBox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.PassBox.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.PassBox.DefaultText = "";
            this.PassBox.FillColor = System.Drawing.Color.White;
            this.PassBox.HideSelection = true;
            this.PassBox.IconLeft = null;
            this.PassBox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.PassBox.IconPadding = 6;
            this.PassBox.IconRight = null;
            this.PassBox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.PassBox.Lines = new string[0];
            this.PassBox.Location = new System.Drawing.Point(175, 97);
            this.PassBox.MaxLength = 32767;
            this.PassBox.MinimumSize = new System.Drawing.Size(1, 1);
            this.PassBox.Modified = false;
            this.PassBox.Multiline = false;
            this.PassBox.Name = "PassBox";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.PassBox.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.PassBox.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.PassBox.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.PassBox.OnIdleState = stateProperties20;
            this.PassBox.Padding = new System.Windows.Forms.Padding(3);
            this.PassBox.PasswordChar = '●';
            this.PassBox.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.PassBox.PlaceholderText = "Enter text";
            this.PassBox.ReadOnly = false;
            this.PassBox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.PassBox.SelectedText = "";
            this.PassBox.SelectionLength = 0;
            this.PassBox.SelectionStart = 0;
            this.PassBox.ShortcutsEnabled = true;
            this.PassBox.Size = new System.Drawing.Size(443, 37);
            this.PassBox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.PassBox.TabIndex = 2;
            this.PassBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.PassBox.TextMarginBottom = 0;
            this.PassBox.TextMarginLeft = 3;
            this.PassBox.TextMarginTop = 0;
            this.PassBox.TextPlaceholder = "Enter text";
            this.PassBox.UseSystemPasswordChar = true;
            this.PassBox.WordWrap = true;
            // 
            // UsernameBox
            // 
            this.UsernameBox.AcceptsReturn = false;
            this.UsernameBox.AcceptsTab = false;
            this.UsernameBox.AnimationSpeed = 200;
            this.UsernameBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.UsernameBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.UsernameBox.BackColor = System.Drawing.Color.Transparent;
            this.UsernameBox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("UsernameBox.BackgroundImage")));
            this.UsernameBox.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.UsernameBox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.UsernameBox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.UsernameBox.BorderColorIdle = System.Drawing.Color.Silver;
            this.UsernameBox.BorderRadius = 15;
            this.UsernameBox.BorderThickness = 1;
            this.UsernameBox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.UsernameBox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.UsernameBox.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.UsernameBox.DefaultText = "";
            this.UsernameBox.FillColor = System.Drawing.Color.White;
            this.UsernameBox.HideSelection = true;
            this.UsernameBox.IconLeft = null;
            this.UsernameBox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.UsernameBox.IconPadding = 10;
            this.UsernameBox.IconRight = null;
            this.UsernameBox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.UsernameBox.Lines = new string[0];
            this.UsernameBox.Location = new System.Drawing.Point(175, 56);
            this.UsernameBox.MaxLength = 32767;
            this.UsernameBox.MinimumSize = new System.Drawing.Size(1, 1);
            this.UsernameBox.Modified = false;
            this.UsernameBox.Multiline = false;
            this.UsernameBox.Name = "UsernameBox";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.UsernameBox.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.UsernameBox.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.UsernameBox.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.UsernameBox.OnIdleState = stateProperties24;
            this.UsernameBox.Padding = new System.Windows.Forms.Padding(3);
            this.UsernameBox.PasswordChar = '\0';
            this.UsernameBox.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.UsernameBox.PlaceholderText = "Enter text";
            this.UsernameBox.ReadOnly = false;
            this.UsernameBox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.UsernameBox.SelectedText = "";
            this.UsernameBox.SelectionLength = 0;
            this.UsernameBox.SelectionStart = 0;
            this.UsernameBox.ShortcutsEnabled = true;
            this.UsernameBox.Size = new System.Drawing.Size(443, 37);
            this.UsernameBox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.UsernameBox.TabIndex = 1;
            this.UsernameBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.UsernameBox.TextMarginBottom = 0;
            this.UsernameBox.TextMarginLeft = 3;
            this.UsernameBox.TextMarginTop = 0;
            this.UsernameBox.TextPlaceholder = "Enter text";
            this.UsernameBox.UseSystemPasswordChar = false;
            this.UsernameBox.WordWrap = true;
            // 
            // Users
            // 
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.ClientSize = new System.Drawing.Size(790, 700);
            this.Controls.Add(this.bunifuShadowPanel6);
            this.Controls.Add(this.CustomersDataGridView);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "Users";
            this.Text = "Users";
            this.bunifuShadowPanel6.ResumeLayout(false);
            this.bunifuShadowPanel6.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.CustomersDataGridView)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuShadowPanel bunifuShadowPanel6;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton AddButton;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton ClearButton;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton RemoveButton;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton UpdateButton;
        private Bunifu.UI.WinForms.BunifuTextBox ConfirmBox;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuTextBox PassBox;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuTextBox UsernameBox;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel6;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.Framework.UI.BunifuElipse bunifuElipse1;
        private Bunifu.UI.WinForms.BunifuDataGridView CustomersDataGridView;
    }
}